//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurfBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalHistory
    {
        public int Id { get; set; }
    
        public virtual Rig Rig { get; set; }
        public virtual Hour Hour { get; set; }
        public virtual Client Client { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
