//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurfBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wetsuit : Equipment
    {
        public int Wetsuit_id { get; set; }
        public string Size { get; set; }
        public Nullable<bool> Type { get; set; }
    }
}
